# ═══════════════════════════════════════════════════════════════════════
# STO-SFO PT-MCMC
# ═══════════════════════════════════════════════════════════════════════
mode: pt_mcmc

dataset_name: stfo
cif_dir:      ./data/CIF_SrTiO-SrFeO
csv_path:     ./data/CIF_SrTiO-SrFeO/detailed_info.csv
spin_pkl:     ./data/CIF_SrTiO-SrFeO/spin_info.pkl
id_col:       id
comp_regex:   '_(\d+)'

species_map:
  22: 0   # Ti
  26: 1   # Fe
  8:  2   # O
  0: 3   # Vo (Xe)
n_atoms:  160
has_spin: true

pt_mcmc:
  cif_path:       ./data/CIF/387.cif
  atom_init_path: ./data/CIF/atom_init.json
  model_ckpt:     ./checkpoints_total_ising_raw_deep/best_model.pkl

  batch_size:     3000
  n_steps:        100000
  t_min:          200.0
  t_max:          1500.0
  chunk_size:     200
  swap_interval:  10

  burnin_chunks:  200
  save_every:     10
  output:         pt_result.npz

  matmul_precision: float32
  enable_x64:      false
